= cljdoc-analyzer
:toc:
:toclevels: 4

WARNING: PRE-ALPHA work here.

== Rationale

A library to return public APIs for Clojure/ClojureScript projects. Recognizes that publics APIs can be altered at load
time by tools such as import-vars.

Cljdoc-analyzer's first use is for cljdoc but others might find value in this library as well.

== History

Some Clojure/ClojureScript projects alter their metadata at load time through tools such as
https://github.com/ztellman/potemkin[potemkin import-vars].

https://github.com/weavejester/codox[Codox] was coded to understand altered metadata for the Clojure projects it
documents. Historically, cljdoc took advantage of these smarts via a branch on a fork of codox to get the metadata it
needed to document Clojure/ClojureScript project APIs. This branch also has an unmerged PR to that understands
ClojureScript import-vars type metadata manipulation.

This library picks up from the cljdoc codox unmerged PR. It extracts the analysis portion of codox and leaves the rest
behind.

See link:doc/design/01-migration-from-analysis-runner.adoc[migration from analisys runner] for more details.

== Usage

=== cljdoc use

Cljdoc-analyzer's first customer is cljdoc. This usage does not cater to general usability. Cljdoc started with using
conventional command line arguments but then switched to edn because it made more sense for its use case.

Example of analyzing cljfmt v0.6.4:
[source,bash,options="nowrap"]
----
clojure -m cljdoc-analyzer.cljdoc-main \
  '{:project "cljfmt/cljfmt" :version "0.6.4" :jarpath "http://repo.clojars.org/cljfmt/cljfmt/0.6.4/cljfmt-0.6.4.jar" :pompath "http://repo.clojars.org/cljfmt/cljfmt/0.6.4/cljfmt-0.6.4.pom"}'
----

This will log to stdout and, if successful, write to a file in a predefined known spot, as indicated in the output logs:
[source,options="nowrap"]
----
2019-08-26 14:22:28,061 INFO  cljdoc-analyzer.runner - results file: /tmp/cljdoc/analysis-out/cljdoc-edn/cljfmt/cljfmt/0.6.4/cljdoc.edn
----

=== general use
You can use cljdoc-analyzer ad hoc to get data for a project published to a maven repo. For example:

[source,bash,no-wrap]
----
clojure -m cljdoc-analyzer.main analyze \
  --project io.aviso/pretty --version "0.1.29" \
  --output-filename "io-aviso-pretty-0.1.29.edn"
----
If everything works, you'll find the output in the current directory in `io.aviso-pretty-0.1.29.edn`

If you are working on a local project, publish it to your local maven repo first, then run the cljdoc analyze command.

There is no facility yet for specifying different repos than the default repos cljdoc-analyzer knows about - if you need
to do this hacking the code might make sense.

We can look at other features as we get a feel for what folks are interested in.

== Output format

The output is a map of namespaces and their publics.

=== edn encoding

The edn has a twist. Function arglists can sometimes contain regular expressions. Since edn does not support
deserializing serialized regular expressions, we adapt by serializing regexes as `#regex` followed by the string
version of regex. For example
----
#".*booya.*"
----
is serialized as:
----
#regex ".*booya.*"
----
See `cljdoc-analyzer.util/serialize-cljdoc-edn` and `cljdoc-analyzer.util/deserialize-cljdoc-edn`.

=== map

The edn output is a map of:

* `:group-id` project group-id
* `:artifact-id` project artifact-id
* `:version` project version
;; TODO: check impact of changing :codox to something else.
* `:codox` codox analysis for languages which can consist of a map with none, one or both of:
** `:clj` list of namespaces (see below)
** `:cljs` list of namespaces (see below)
* `:pom-str` slurp of maven pom file

list of namespaces is a list of maps of:

** `:name` namespace name
** `:doc` namespace doc string
** `:publics` namespace publics which is a list of maps of:
*** `:name` public element name
*** `:type` one of: `:macro` `:multimethod` `:protocol` `:var`
*** `:doc`  doc string
*** `:file` file relative to jar root
*** `:line` line number
*** `:arglists` list of vectors of arglists, omitted for `def` `record` and `protocol` elements
*** `:members`  only applicable when `:type` is `:protocol`, list of maps of:
**** `:arglists`  list of vectors of arglists
**** `:name` name of protocol method
**** `:type` can this be only `:var`?

special metadata tags when present are included in publics:

* `:added` version an element was added
* `:deprecated` version an element was deprecated
* `:dynamic` for dynamic defs

== Internal Workings

We use `clojure.tools.namespace` and `cljs.analyzer.api` to load source and collect metadata. This requires the loading
of a project's dependencies. To avoid dependency conflicts and confusion, we keep dependencies at a minimum during
metadata collection time by splitting the work into two distinct phases.

. Prepare for analysis - the source for this work can be found under link:src[src]. Here we do everything we can to prepare for
  metadata collection.
. Collect metadata - the source for this work can be found under link:metagetta[metagetta]. A separate metagetta process
  is launched to collect metadata on sources prepared in step 1.


== Testing

We make use of https://github.com/lambdaisland/kaocha[kaocha] for testing.

Metagetta is a separate sub-project with its own unit tests. To run metagetta unit tests:
----
cd metagetta
clojure -A:test
----

Cljdoc-analyzer has integration and unit tests, to run them all, ensure you are in cljdoc-analyzer root dir and:
----
clojure -A:test
----

The integration tests can take a while to run, to run unit tests only:
----
clojure -A:test unit
----

To run integration tests only:
----
clojure -A:test integration
----

To automatically rerun tests on any changes, tack on a `--watch` to any of the above commands. See kaocha docs for other options.


== Notes preserved from codox docs
TODO: Directly from codox README... Not sure of relevance... need to understand.

=== AOT Compilation

AOT-compiled namespaces will lose their metadata, which mean you'll
lose documentation for namespaces. Avoid having global `:aot`
directives in your project; instead, place them in a specialized
profile, such as `:uberjar`.


== Metadata Examples

Cljdoc analyzer will recognize the following metadata.

=== :no-doc
The `:no-doc` metadata key is a convention invented by codox to indicate that an element should not be included in api documentation.

Examples:

[source,clojure]
----
;; Documented
(defn square
  "Squares the supplied number."
  [x]
  (* x x))

;; Not documented
(defn ^:no-doc hidden-square
  "Squares the supplied number."
  [x]
  (* x x))
----

`:no-doc` can also be used at the namespace level:

For example:

[source,clojure]
----
(ns ^:no-doc hidden-ns)
----

=== :added

To denote the library version the var was added in, use the `:added` metadata key:

[source,clojure]
----
(defn square
  "Squares the supplied number."
  {:added "1.0"}
  [x]
  (* x x))
----

=== :deprecated

Similar to `:added`, deprecated vars can be denoted with the `:deprecated` metadata key:

[source,clojure]
----
(defn square
  "Squares the supplied number."
  {:deprecated "2.0"}
  [x]
  (* x x))
----

== Licenses

Based on https://github.com/weavejester/codox[Codox]:

* Copyright © 2018 James Reeves
* Distributed under the Eclipse Public License either version 1.0 or (at your option) any later version.
