* What to do with shared code?
  I have copied in code from cljdoc shared-utils, which is not ideal.
  Verify if it is really shared.
  If so... create a new lib?
  Or bring cljdoc-analyzer in under existing analysis runner module. I'd prefer a separate project to encourage reuse tho.
* [resolved] Why is repos currently external to runner?
   I'm not sure.
   These are the base maven repos to use and is currently:

   :maven-repositories [{:id "clojars" :url "https://repo.clojars.org/"}
                        {:id "central" :url "http://central.maven.org/maven2/"}]

   But deps.clj has default repos:

   (def ^:private default-repos
     {"central" {:url "https://repo1.maven.org/maven2/"},
      "clojars" {:url "https://repo.clojars.org/"}
      ;; Included to account for https://dev.clojure.org/jira/browse/TDEPS-46
      ;; specifically anything depending on org.immutant/messaging will fail
      ;; this includes compojure-api
      "jboss" {:url "https://repository.jboss.org/nexus/content/groups/public/"}
      ;; included for https://github.com/FundingCircle/jackdaw
      "confluent" {:url "https://packages.confluent.io/maven/"}})

   Which repeats "clojars" and overrides "central".

   So it looks to  me, like I can ignore repos. I think it can safely be removed from cljdoc config.
* Why are jar and pom passsed into runner?
   Is pom not always included in jar for clojure projects?  Maybe not. I shall assume not for now.
* Why are project (group-id/artifact-id) and version passed into runner?
   Can't I glean these from jar and/or pom?  Maybe not? I shall asumme not for now.
* Reintroduce hardcoded config
   The hardcoded config specifies overrides for specific projects with regards to both api analysis and doc parsing.
   I'll need to separate the two. I am only interested in api analysis.
* Include args used in result?
   Might be nice to know what :namespaces and :languages were requested (Actually did I accidentally turf this?)
* printlns are a bit odd for general consumption
   switch to logging?
   provide a quiet option?
* edn only as commandline perhaps a bit awkward
   totally appropriate for cljdoc usage.
   but for general usage might be a bit awkward
