#!/usr/bin/env bash

# cljdoc-analyzer internal metagetta sub-project is linted along with cljdoc-analyzer

set -eou pipefail

function lint() {
    local lint_args
    if [ ! -d .clj-kondo/.cache ]; then
        echo "--[linting and building cache]--"
        # classpath with tests paths
        local classpath;classpath="$(clojure -A:test -Spath)"
        lint_args="$classpath"
    else
        echo "--[linting]--"
        lint_args="src test modules/metagetta"
    fi
    set +e
    clojure -M:clj-kondo \
            --lint ${lint_args} \
            --config '{:output {:include-files ["^src" "^test" "^modules/metagetta"]}}'
    local exit_code=$?
    set -e
    if [ ${exit_code} -ne 0 ] && [ ${exit_code} -ne 2 ] && [ ${exit_code} -ne 3 ]; then
        echo "** clj-kondo exited with unexpected exit code: ${exit_code}"
    fi
    exit ${exit_code}
}

lint
